### ISSUE TITLE
will using this lib solve my issue of window.Intercom is not a function error

### ISSUE THREAD

**Issue by jasan-s** [nhagen/react-intercom#22]
the problem I'm running into when using intercom directly is that I keep getting the error that window.Intercom is not a function because I am async loading the SDK when the main component mounts. Thus its not available in other components at the time of their lifecycle event(component did mount).

**Comment by nhagen** [comment]
Specifically, that error won't happen. Instead you'll get a log message saying [`Intercom has not initialized yet`](https://github.com/nhagen/react-intercom/blob/master/src/index.js#L11) rather than a type error. This component loads the intercom code asyncronously still, so if you're trying to use features before the script has loaded, it likely wont work as expected. Its probably possible to add a queue for events that should be fired once its finished loading, however.
