### ISSUE TITLE
"TypeError: window.Intercom is not a function" after react 16 upgrade

### ISSUE THREAD

**Issue by llaurila** [nhagen/react-intercom#41]
I upgraded my NextJS project to NextJS 4 & React 16 and react-intercom stopped working. Gives

TypeError: window.Intercom is not a function

on browser-side.

Any ideas?

**Comment by bsonntag** [comment]
The Intercom initialization code should be moved from the constructor to the `componentDidMount` method.

**Comment by nhagen** [comment]
@bsonntag good point, looking at the code now I'm not sure if there was some reason for it being in the constructor or than because `constructor` is called once which is convenient. Since putting the tag on the page is a side effect, I would expect it to be in `componentDidMount`, and I would consider moving it to `componentDidMount,`. But this point seems kind of theoretical. its not clear to me how @llaurila's issue would be resolved by this. Can you elaborate? The cosntructor should be called before `componentDidMount`in any case.

**Comment by bsonntag** [comment]
@nhagen I'm sorry, I thought this error was on the server.

**Comment by jefflewis** [comment]
I was running into this... I had created an activator for intercom with an id of "Intercom". This conflicted with window.Intercom. Changing my selector to `<a id="intercom_help>Help Me</a>` resolved my issues.

**Comment by WatsonFungHK** [comment]
You can avoid this kind of error by checking the existence of window before doing something on it
`
if (!!window.Intercom) {
  window.Intercom( /* what you want to do */);
}
`
