### ISSUE TITLE
React 16.9 - Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by bluepeter** [nhagen/react-intercom#71]
See https://fb.me/react-async-component-lifecycle-hooks and https://reactjs.org/blog/2019/08/08/react-v16.9.0.html for details. At minimum, this needs the prefix `UNSAFE_` adding to these calls.

![intercom](https://user-images.githubusercontent.com/2158187/63060504-5405e880-bea7-11e9-8d6e-857c323d5ab0.png)

**Comment by nhagen** [comment]
This should be addressed by #73

**Comment by tony-scio** [comment]
Looking forward to 2.0 :)

**Comment by devrnt** [comment]
@tony-scio 
I'm keen to announce that I've released a React Intercom integration:   
https://github.com/devrnt/react-use-intercom

**Features**
* Hooks
* Written in TypeScript
* Documented, self explaining methods

**Motivation**
I've found it not very developer friendly to integrate Intercom in a React application.

**Note**
I don't want to spam this issue with advertisement, that's why I'll delete this message in the near future.
